spring.application.name=TodoList

spring.data.mongodb.uri=mongodb://localhost:27017/TodoList
spring.data.mongodb.auto-index-creation=true

logging.level.root=INFO
logging.level.com.ishant.TodoList=DEBUG
